"""Generate settings.lua from a settings dict."""

from __future__ import annotations

import re
from typing import Any

HEADER = """\
-- Generated by wezterm-tui. Do not edit manually.
-- Source of truth: settings.json
local wezterm = require("wezterm")
local M = {}
"""

FOOTER = "\nreturn M\n"

DIRECT_MAP: dict[str, list[tuple[str, str]]] = {
    "colors": [("color_scheme", "color_scheme")],
    "window": [("padding", "window_padding"), ("decorations", "window_decorations"),
               ("background_opacity", "window_background_opacity"), ("initial_cols", "initial_cols"),
               ("initial_rows", "initial_rows")],
    "tabs": [("enable_tab_bar", "enable_tab_bar"), ("use_fancy_tab_bar", "use_fancy_tab_bar"),
             ("tab_bar_at_bottom", "tab_bar_at_bottom"), ("hide_tab_bar_if_only_one_tab", "hide_tab_bar_if_only_one_tab"),
             ("show_new_tab_button_in_tab_bar", "show_new_tab_button_in_tab_bar"),
             ("show_close_tab_button_in_tabs", "show_close_tab_button_in_tabs"),
             ("show_tab_index_in_tab_bar", "show_tab_index_in_tab_bar"), ("tab_max_width", "tab_max_width")],
    "cursor": [("default_cursor_style", "default_cursor_style"), ("cursor_blink_rate", "cursor_blink_rate"),
               ("cursor_blink_ease_in", "cursor_blink_ease_in"), ("cursor_blink_ease_out", "cursor_blink_ease_out"),
               ("cursor_thickness", "cursor_thickness")],
    "scrollback": [("scrollback_lines", "scrollback_lines"), ("enable_scroll_bar", "enable_scroll_bar"),
                   ("scroll_to_bottom_on_input", "scroll_to_bottom_on_input"), ("min_scroll_bar_height", "min_scroll_bar_height")],
    "performance": [("front_end", "front_end"), ("max_fps", "max_fps"), ("animation_fps", "animation_fps"),
                    ("webgpu_power_preference", "webgpu_power_preference")],
    "mouse": [("pane_focus_follows_mouse", "pane_focus_follows_mouse"), ("hide_mouse_cursor_when_typing", "hide_mouse_cursor_when_typing"),
              ("swallow_mouse_click_on_pane_focus", "swallow_mouse_click_on_pane_focus"),
              ("swallow_mouse_click_on_window_focus", "swallow_mouse_click_on_window_focus"),
              ("mouse_wheel_scrolls_tabs", "mouse_wheel_scrolls_tabs")],
    "misc": [("audible_bell", "audible_bell"), ("check_for_updates", "check_for_updates"),
             ("automatically_reload_config", "automatically_reload_config"), ("term", "term"),
             ("exit_behavior", "exit_behavior"), ("canonicalize_pasted_newlines", "canonicalize_pasted_newlines"),
             ("enable_wayland", "enable_wayland"), ("enable_kitty_keyboard", "enable_kitty_keyboard"),
             ("quick_select_patterns", "quick_select_patterns")],
}

SECTION_LABELS = {
    "font": "Font", "colors": "Colors", "window": "Window", "tabs": "Tabs",
    "cursor": "Cursor", "scrollback": "Scrollback", "performance": "Performance",
    "keybindings": "Keybindings", "mouse": "Mouse", "misc": "Misc",
}


def _lua_value(value: Any) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, int):
        return str(value)
    if isinstance(value, float):
        if value == int(value):
            return f"{value:.1f}"
        return str(value)
    if isinstance(value, str):
        escaped = (value
                   .replace("\\", "\\\\")
                   .replace('"', '\\"')
                   .replace("\n", "\\n")
                   .replace("\r", "\\r")
                   .replace("\0", "\\0"))
        return f'"{escaped}"'
    if isinstance(value, list):
        if not value:
            return "{}"
        items = ", ".join(_lua_value(v) for v in value)
        return "{ " + items + " }"
    if isinstance(value, dict):
        parts = [f"{k} = {_lua_value(v)}" for k, v in value.items()]
        return "{ " + ", ".join(parts) + " }"
    return str(value)


_ACTION_RE = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")


def _lua_action(binding: dict) -> str:
    action = binding["action"]
    if not _ACTION_RE.match(action):
        raise ValueError(f"Invalid action name: {action!r}")
    args = binding.get("args")
    if args is None:
        return f"wezterm.action.{action}"
    if isinstance(args, str):
        return f'wezterm.action.{action}({_lua_value(args)})'
    if isinstance(args, dict):
        parts = [f"{k} = {_lua_value(v)}" for k, v in args.items()]
        return f"wezterm.action.{action}({{ {', '.join(parts)} }})"
    if isinstance(args, bool):
        return f"wezterm.action.{action}({_lua_value(args)})"
    if isinstance(args, (int, float)):
        return f"wezterm.action.{action}({args})"
    return f"wezterm.action.{action}"


def generate_lua(settings: dict) -> str:
    lines: list[str] = [HEADER]

    # Font (special)
    font = settings.get("font", {})
    family = font.get("family", "JetBrains Mono")
    weight = font.get("weight", "Regular")
    lines.append("-- Font")
    lines.append(f'M.font = wezterm.font({_lua_value(family)}, {{ weight = {_lua_value(weight)} }})')
    if "size" in font:
        lines.append(f"M.font_size = {_lua_value(font['size'])}")
    if "line_height" in font:
        lines.append(f"M.line_height = {_lua_value(font['line_height'])}")
    if font.get("harfbuzz_features"):
        lines.append(f"M.harfbuzz_features = {_lua_value(font['harfbuzz_features'])}")
    lines.append("")

    # Direct-mapped sections
    for section in ["colors", "window", "tabs", "cursor", "scrollback", "performance"]:
        if section not in settings or section not in DIRECT_MAP:
            continue
        lines.append(f"-- {SECTION_LABELS[section]}")
        data = settings[section]
        for json_key, lua_key in DIRECT_MAP[section]:
            if json_key in data:
                lines.append(f"M.{lua_key} = {_lua_value(data[json_key])}")
        lines.append("")

    # Keybindings (special)
    keybindings = settings.get("keybindings", [])
    if keybindings:
        lines.append("-- Keybindings")
        lines.append("M.keys = {")
        for binding in keybindings:
            key = binding["key"]
            mods = binding.get("mods", "")
            action_lua = _lua_action(binding)
            if mods:
                lines.append(f'  {{ key = {_lua_value(key)}, mods = {_lua_value(mods)}, action = {action_lua} }},')
            else:
                lines.append(f'  {{ key = {_lua_value(key)}, action = {action_lua} }},')
        lines.append("}")
        lines.append("")

    # Mouse + Misc
    for section in ["mouse", "misc"]:
        if section not in settings or section not in DIRECT_MAP:
            continue
        lines.append(f"-- {SECTION_LABELS[section]}")
        data = settings[section]
        for json_key, lua_key in DIRECT_MAP[section]:
            if json_key in data:
                lines.append(f"M.{lua_key} = {_lua_value(data[json_key])}")
        lines.append("")

    lines.append(FOOTER.lstrip("\n"))
    return "\n".join(lines)
