import base64
import json

from wezterm_tui.export import export_json, export_base64, import_base64


def test_export_json():
    settings = {"font": {"size": 14}, "colors": {"color_scheme": "Dracula"}}
    result = export_json(settings)
    parsed = json.loads(result)
    assert parsed == settings


def test_export_base64_roundtrip():
    settings = {"font": {"size": 14}, "colors": {"color_scheme": "Dracula"}}
    blob = export_base64(settings)
    restored = import_base64(blob)
    assert restored == settings


def test_export_base64_is_url_safe():
    settings = {"font": {"family": "JetBrains Mono"}, "_version": 1}
    blob = export_base64(settings)
    assert "+" not in blob
    assert "/" not in blob


def test_import_base64_invalid():
    assert import_base64("not-valid-base64!!!") is None


def test_export_lua_uses_generate_lua():
    from wezterm_tui.export import export_lua
    from wezterm_tui.schema import get_defaults

    settings = get_defaults()
    settings["_version"] = 1
    result = export_lua(settings)
    assert "Generated by wezterm-tui" in result
    assert "return M" in result
