# tests/test_lua_gen.py
from wezterm_tui.lua_gen import generate_lua
from wezterm_tui.schema import get_defaults


def _make_settings(**overrides) -> dict:
    """Create a full settings dict from defaults, applying overrides."""
    settings = get_defaults()
    settings["_version"] = 1
    for key, value in overrides.items():
        if isinstance(value, dict) and key in settings and isinstance(settings[key], dict):
            settings[key].update(value)
        else:
            settings[key] = value
    return settings


def test_generate_lua_basic_scalars():
    settings = _make_settings(
        font={"family": "Fira Code", "weight": "Bold", "size": 14.0, "line_height": 1.2, "harfbuzz_features": []},
        colors={"color_scheme": "Catppuccin Mocha"},
        window={"padding": {"left": 8, "right": 8, "top": 8, "bottom": 8},
                "decorations": "TITLE | RESIZE", "background_opacity": 0.95,
                "initial_cols": 140, "initial_rows": 40},
        tabs={"enable_tab_bar": True, "use_fancy_tab_bar": False, "tab_bar_at_bottom": True,
              "hide_tab_bar_if_only_one_tab": True, "tab_max_width": 25},
        keybindings=[{"key": "=", "mods": "CTRL", "action": "IncreaseFontSize"}],
    )
    lua = generate_lua(settings)

    assert "Generated by wezterm-tui" in lua
    assert 'local wezterm = require("wezterm")' in lua
    assert 'M.font = wezterm.font("Fira Code", { weight = "Bold" })' in lua
    assert "M.font_size = 14.0" in lua
    assert "M.enable_tab_bar = true" in lua
    assert "M.use_fancy_tab_bar = false" in lua
    assert "M.window_padding = { left = 8, right = 8, top = 8, bottom = 8 }" in lua
    assert "wezterm.action.IncreaseFontSize" in lua
    assert lua.strip().endswith("return M")


def test_generate_lua_keybinding_with_string_arg():
    settings = _make_settings(
        keybindings=[{"key": "h", "mods": "CTRL|SHIFT", "action": "ActivatePaneDirection", "args": "Left"}],
    )
    lua = generate_lua(settings)
    assert 'wezterm.action.ActivatePaneDirection("Left")' in lua


def test_generate_lua_keybinding_with_table_arg():
    settings = _make_settings(
        keybindings=[{"key": "d", "mods": "CTRL|SHIFT", "action": "SplitHorizontal", "args": {"domain": "CurrentPaneDomain"}}],
    )
    lua = generate_lua(settings)
    assert 'wezterm.action.SplitHorizontal({ domain = "CurrentPaneDomain" })' in lua
